### ISSUE TITLE
[SOLVED] Unauthorized Message

### ISSUE THREAD

**Issue by deadfishhackers** [HiruNya/HentaiBot#11]
root@brunnyinc ~ python3.6 HentaiBot.py 
**Error!   To Channel: 511433861297864704,    Sent 'Urotsukidoji: New Saga 3'
{"code": 40001, "message": "Unauthorized"}**

Can anyone help me?
And my OS is Kali Linux

**Comment by deadfishhackers** [comment]
I accidentally removed the last number on my token

**Comment by HiruNya** [comment]
Found two problems:
1. Discord doesn't always reply with the ratelimit headers in the case of errors.
2. Discord requires the token to be connected via websocket first, otherwise it returns a ``4001: "Unauthorised"``.

I'll keep this issue open until I fix this.

**Comment by HiruNya** [comment]
#12
