### ISSUE TITLE
[SOLVED] I got another error can anyone help

### ISSUE THREAD

**Issue by deadfishhackers** [HiruNya/HentaiBot#12]
My Operating System Is kali linux i just customized it

┌─[root@deadfishhackers]─[~/T00LS/HentaiBot]
└──╼ #python3.6 HentaiBot.py 
**Exception in thread HAnime:**
**Traceback (most recent call last):**
  _**File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/T00LS/HentaiBot/src/hanime.py", line 26, in run
    last_entry=self.last_entry
  File "/root/T00LS/HentaiBot/src/hanime.py", line 70, in go
    embed=e
  File "/root/T00LS/HentaiBot/src/discord.py", line 43, in send_msg
    self.reset_remaining = int(response.headers["X-RateLimit-Remaining"])
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-ratelimit-remaining'**_

**Comment by HiruNya** [comment]
Is your Discord Token correct?
You get a token by going to https://discordapp.com/developers/applications/ -> "Create an application" -> Bot -> (You might need to build a bot here) -> "Click to reveal token".
You'll also need to add your bot to your server so it can post on the specific channel.

**Comment by deadfishhackers** [comment]
Yes my discord bot is correct and i did add my bot to server

**Comment by deadfishhackers** [comment]
Hey i solved error my self can you say the reason why the script freezes at this moment?

┌─[root@deadfishhackers]─[~/T00LS/HentaiBot]
└──╼ #python3.6 HentaiBot.py 
Info     No New HAnime Entries

**Comment by HiruNya** [comment]
By freeze do you mean that the script never returns and runs continuously or does the script return but with no output after that line?
Each process (HentaiHaven, HAnime, and the subreddits) are done on their own thread so that would explain why the HAnime one is working, so the problem must be from from the HAnime or subreddits.
I'm assuming from the other post, where it says ``Info HentaiHaven id changed to: 88887``, that you also have the HentaiHaven process working. Are you checking any subreddits aswell?

**Comment by deadfishhackers** [comment]
ok i waited some time and this happend 

┌─[✗]─[root@deadfishhackers]─[~/T00LS/HentaiBot]
└──╼ #python3.6 HentaiBot.py 
Info     No New HentaiHaven Entries
Exception in thread HAnime:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/T00LS/HentaiBot/src/hanime.py", line 26, in run
    last_entry=self.last_entry
  File "/root/T00LS/HentaiBot/src/hanime.py", line 70, in go
    embed=e
  File "/root/T00LS/HentaiBot/src/discord.py", line 43, in send_msg
    self.reset_remaining = int(response.headers["X-RateLimit-Remaining"])
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'x-ratelimit-remaining'

**Comment by HiruNya** [comment]
I made a debug branch that ignores the rate limit, so try and switch to that branch so we can see what error discord sends back.
[Here's the branch](https://github.com/HiruNya/HentaiBot/tree/debug)
(You should be able to access it by ``git pull`` and then ``git checkout debug``.)

**Comment by deadfishhackers** [comment]
can u add me on discord so i can send screenshots?
and can u give me the full command?

**Comment by HiruNya** [comment]
Found two problems:
1. Discord doesn't always reply with the ratelimit headers in the case of errors.
2. Discord requires the token to be connected via websocket first, otherwise it returns a ``4001: "Unauthorised"``.

I'll keep this issue open until I fix this.

**Comment by HiruNya** [comment]
Updated the bot, everything should be fixed now.
