### ISSUE TITLE
KeyError: 'src'

### ISSUE THREAD

**Issue by 31ank** [HiruNya/HentaiBot#5]
Error while using Python3.6.4

``Traceback (most recent call last):
  File "HentaiBot.py", line 214, in <module>
    start()
  File "HentaiBot.py", line 113, in start
    desc, image = get_from_summary(y.summary)
  File "HentaiBot.py", line 15, in get_from_summary
    i = root[0].attrib["src"]
KeyError: 'src'``

**Comment by HiruNya** [comment]
The error should be fixed now.
I think it was due to the HentaiHaven RSS feed changing where they put the image.
Thanks for making an issue, if the error still comes up after using the latest version, please tell me.

**Comment by HiruNya** [comment]
I'm assuming the error was fixed so I'm closing this issue. Feel free to open one up again if you still have the problem.
