### ISSUE TITLE
YO

### ISSUE THREAD

**Issue by Angthechicken** [HiruNya/HentaiBot#7]
YO WHAT UP, THE BOT IS SO BAD AND IT NEVER UPLOADS AT 9 EXACTLY, ALWAYS OFF

**Comment by HiruNya** [comment]
Shut up, Ang. Get your hentai like a big boi by using Bing<sup>TM</sup>, Github's recommended porn searching tool. BTW this has nothing to do with the actual program, just that my computer is slow.
